service: default # Id of the service
env: flex       # Flex environment
runtime: java   # Java runtime
runtime_config:
  jdk: openjdk8 # use OpenJDK 8
handlers:
- url: /.*
  script: this field is required, but ignored
  